default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  url: postgresql://localhost/booklessons_development?pool=5
  # user: zhang
  # password: password123
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: booklessons_development

test:
  <<: *default
  database: booklessons_test

production:
  <<: *default
  database: myapp_production
  url: <%= ENV['DATABASE_URL'] %>
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>